version: '3.8'

services:

  db:
    image: mysql:8.0
    container_name: todo_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret123
      MYSQL_DATABASE: tododb
    # ports:
    #   - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-psecret123"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: ./backend
    container_name: todo_backend
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 3001
      APP_NAME: TodoApp
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: secret123
      DB_NAME: tododb
      STUDENT_NAME: Nguyen Van A
      STUDENT_ID: SV123456
      STUDENT_CLASS: CNTT01
    ports:
      - "3001:3001"

  frontend:
    build:
      context: ./frontend
      args:
        VITE_API_URL: http://localhost:3001
    container_name: todo_frontend
    restart: always
    depends_on:
      - backend
    ports:
      - "3000:80"

volumes:
  db_data: